export default {
  systemSelect: 'api/system/select',
  systemConfig: 'api/system/config',
  // 登录页
  login: '/api/auth/login',
  // 用户修改密码
  resetMyPass: 'api/user/my/password/reset',
  // 获取当前中心下的所有课题
  getCenterProject: 'api/center/project',
  // 用户管理
  userList: 'api/user/list',
  addUser: 'api/user/add',
  editUser: 'api/user/edit',
  resetPass: 'api/user/password/reset',
  getDepartments: 'api/hospital/departments',
  // 用户角色
  userRoleAdd: 'api/user/role/add',
  userRoleEdit: 'api/user/role/edit',
  userRoleView: 'api/user/role/view',
  userRoleDelete: 'api/user/role/delete',
  // 用户数据权限
  userDataAdd: 'api/data/user/role/add',
  userDataDelete: 'api/data/user/role/delete',
  userDataView: 'api/data/user/role/view',
  // 角色管理
  roleList: 'api/role/list',
  addRole: 'api/role/add',
  editRole: 'api/role/edit',
  editRolePrivilege: 'api/role/privilege/edit',
  // 数据权限
  dataList: 'api/data/role/list',
  addData: 'api/data/role/add',
  editData: 'api/data/role/edit',
  // 系统
  getProjectUsers: 'api/department/users',
  // 中心管理
  centerList: 'api/center/list',
  addCenter: 'api/center/add',
  editCenter: 'api/center/edit',
  // 课题管理
  projectList: 'api/project/list',
  addProject: 'api/project/add',
  editProject: 'api/project/edit',
  projectUsersList: 'api/project/user/list',
  addProjectUser: 'api/user/project/add',
  deleteProjectUser: 'api/user/project/delete',
  // 课题属性
  projectPropertyList: 'api/label/list',
  addProjectProperty: 'api/label/add',
  editProjectProperty: 'api/label/edit',
  // 标签
  tagList: 'api/tag/list',
  addTag: 'api/tag/add',
  editTag: 'api/tag/edit',
  // 标签属性，没放入权限中
  tagPropertyList: 'api/property/list',
  addTagProperty: 'api/property/add',
  editTagProperty: 'api/property/edit',
  // 评语，没入权限
  commentList: 'api/user/comment/list',
  commentAdd: 'api/user/comment/add',
  commentEdit: 'api/user/comment/edit',
  commentDelete: 'api/user/comment/delete',
  // 标注页面
  projectTag: 'api/project/tags',
  projectLabel: 'api/project/labels',
  // 我的影像
  seriesMyList: 'api/series/my/list',
  getSeriesSave: 'api/series/raw/data',
  seriesSave: 'api/series/label/save',
  seriesAdd: 'api/series/job/add',
  // 全部影像
  seriesList: 'api/series/list',
  // 课题影像
  seriesJobList: 'api/series/job/list',
  // 重标注
  seriesColumn: 'api/series/job/column',
  seriesAddAgain: 'api/series/label/add',
  seriesCheck: 'api/series/job/check',
  seriesConfirm: 'api/series/job/confirm',
  seriesReconfirm: 'api/series/job/reconfirm',
  
  //已标注修改
  seriesLabelEdit: 'api/series/label/edit',
  //已完成再标注
  seriesJobRelabel: 'api/series/job/relabel',
  // 智能识别
  // 甲状腺
  thyroidAnalyse: 'api/thyroid/analyse',
  getThyroidModules: 'api/thyroid/modules',
  thyroidMyList: 'api/thyroid/my/list',
}

